name: CI
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"
jobs:
  tests:
    name: Unit and integrations tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.17, 1.18, 1.19]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          sudo /etc/init.d/mysql start
          while ! mysqladmin ping --silent; do
            sleep 1
          done
          sudo mysql -proot -e 'CREATE DATABASE goyave CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
          sudo mysql -proot -e 'CREATE USER "goyave"@"%" IDENTIFIED BY "secret"'
          sudo mysql -proot -e 'GRANT ALL PRIVILEGES ON goyave.* TO "goyave"@"%"'
          go test -v -p 1 -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - if: ${{ matrix.go == 1.19 }}
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.txt

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.49
          args: --timeout 5m
